import blogimages from "../../../../assets/blog/blogimages.jpg";

export const TechTalksData = [
  {
    id: 1,
    image: blogimages,
    title: "Our Category Choices for Top 10 Tech Gadgets in 2023",
    category: "Gadgets",
    postedBy: "Alexa",
    date: "10 April 2023",
  },
  {
    id: 2,
    image: blogimages,
    title: "How to Choose the Right Laptop for Your Needs: Our Expert Says",
    category: "News",
    postedBy: "Rumi",
    date: "12 April 2023",
  },
  {
    id: 3,
    image: blogimages,
    title: "High Quality vs Price: Why You Should Upgrade to A Smart TV?",
    category: "Tips",
    postedBy: "Alexa",
    date: "14 April 2023",
  },
  {
    id: 4,
    image: blogimages,
    title: "The Ultimate Guide to Tech Cyber Monday Shopping for You",
    category: "Tips",
    postedBy: "Mamudul",
    date: "16 April 2023",
  },
  {
    id: 5,
    image: blogimages,
    title: "Learning about The Future of Smart Office Technology",
    category: "Gadgets",
    postedBy: "Rihana",
    date: "18 April 2023",
  },
  {
    id: 6,
    image: blogimages,
    title: "What to Expect from AI-Powered Homes by 2025",
    category: "Guide",
    postedBy: "Mithu",
    date: "20 April 2023",
  },
  {
    id: 7,
    image: blogimages,
    title: "Smartphone Trends: Foldables, AI Cameras & More",
    category: "Gadgets",
    postedBy: "Dhune",
    date: "22 April 2023",
  },
  {
    id: 8,
    image: blogimages,
    title: "A Beginner's Guide to Building Your Own PC",
    category: "Guide",
    postedBy: "Farzana",
    date: "24 April 2023",
  },
  {
    id: 9,
    image: blogimages,
    title: "Top 5 Tech Myths You Still Believe",
    category: "Tips",
    postedBy: "Jamil",
    date: "26 April 2023",
  },
  {
    id: 10,
    image: blogimages,
    title: "Is Your Wi-Fi Router Slowing You Down? Here's Why",
    category: "News",
    postedBy: "Tanvir",
    date: "28 April 2023",
  },
  {
    id: 11,
    image: blogimages,
    title: "The Rise of Wearable Tech: What’s New in 2023?",
    category: "Gadgets",
    postedBy: "Alexa",
    date: "30 April 2023",
  },
  {
    id: 12,
    image: blogimages,
    title: "Top Cloud Storage Services Compared: Which Should You Choose?",
    category: "Guide",
    postedBy: "Rumi",
    date: "02 May 2023",
  },
  {
    id: 13,
    image: blogimages,
    title: "Why Battery Tech is the Future of Innovation",
    category: "News",
    postedBy: "Mithu",
    date: "04 May 2023",
  },
  {
    id: 14,
    image: blogimages,
    title: "How to Protect Your Smart Devices from Hackers",
    category: "Tips",
    postedBy: "Mamudul",
    date: "06 May 2023",
  },
  {
    id: 15,
    image: blogimages,
    title: "Tech on the Road: Smart Cars and Connected Vehicles",
    category: "Gadgets",
    postedBy: "Rihana",
    date: "08 May 2023",
  },
  {
    id: 16,
    image: blogimages,
    title: "Remote Work Essentials: Top Devices to Stay Productive",
    category: "Guide",
    postedBy: "Dhune",
    date: "10 May 2023",
  },
  {
    id: 17,
    image: blogimages,
    title: "Exploring the World of Quantum Computing",
    category: "News",
    postedBy: "Tanvir",
    date: "12 May 2023",
  },
  {
    id: 18,
    image: blogimages,
    title: "Augmented Reality Glasses: Hype or the Future?",
    category: "Gadgets",
    postedBy: "Jamil",
    date: "14 May 2023",
  },
  {
    id: 19,
    image: blogimages,
    title: "Smart Kitchens: The Future of Cooking is Here",
    category: "Tips",
    postedBy: "Farzana",
    date: "16 May 2023",
  },
  {
    id: 20,
    image: blogimages,
    title: "2023 Tech Gift Guide: What to Buy for Every Budget",
    category: "Guide",
    postedBy: "Alexa",
    date: "18 May 2023",
  },
];
