import Productimg from "../../../../assets/Productimg/Productimg.webp"

export const Featureddata = [
  {
    id: 1,
    imges: Productimg,
    pCategory: "Phone",
    pName: "iPhone 15 Pro Max",
    rate: 4.7, 
    totalrating: 1248,
    price: 1199.99,
    discout: 10,
    size: "6.7 inches",
    variant: ["Space Black", "Titanium", "Silver"],
    weight: "221g",
    brand: "Apple",
    delivery: "1-2 business days",
    description: "The iPhone 15 Pro Max features a titanium design, A17 Pro chip, and the most advanced camera system ever on iPhone with a 5x Telephoto camera.",
  },
  {
    id: 2,
    imges: Productimg,
    pCategory: "Phone",
    pName: "Samsung Galaxy S23 Ultra",
    rate: 4.6,
    totalrating: 987,
    price: 1099.99,
    discout: 15,
    size: "6.8 inches",
    variant: ["Phantom Black", "Cream", "Green"],
    weight: "234g",
    brand: "Samsung",
    delivery: "2-3 business days",
    description: "Galaxy S23 Ultra with built-in S Pen, 200MP camera, and the fastest Snapdragon processor yet for Galaxy.",
  },
  {
    id: 3,
    imges: Productimg,
    pCategory: "Phone",
    pName: "Google Pixel 8 Pro",
    rate: 4.5,
    totalrating: 756,
    price: 999.00,
    discout: 12,
    size: "6.7 inches",
    variant: ["Obsidian", "Porcelain", "Bay"],
    weight: "213g",
    brand: "Google",
    delivery: "3-5 business days",
    description: "Pixel 8 Pro with Google AI, powerful camera system, and the most advanced Pixel features yet.",
  },
  {
    id: 4,
    imges: Productimg,
    pCategory: "Computers & Tablets",
    pName: "MacBook Pro 16-inch",
    rate: 4.8,
    totalrating: 876,
    price: 2499.00,
    discout: 5,
    size: "16.2 inches",
    variant: ["Space Gray", "Silver"],
    weight: "2.1kg",
    brand: "Apple",
    delivery: "1-3 business days",
    description: "MacBook Pro with M2 Pro or M2 Max chip for extreme performance and battery life.",
  },
  {
    id: 5,
    imges: Productimg,
    pCategory: "Computers & Tablets",
    pName: "Microsoft Surface Pro 9",
    rate: 4.3,
    totalrating: 543,
    price: 999.99,
    discout: 20,
    size: "13 inches",
    variant: ["Platinum", "Graphite", "Sapphire"],
    weight: "879g",
    brand: "Microsoft",
    delivery: "2-4 business days",
    description: "Surface Pro 9 combines tablet portability with laptop performance and optional 5G connectivity.",
  },
  {
    id: 6,
    imges: Productimg,
    pCategory: "Computers & Tablets",
    pName: "iPad Pro 12.9-inch",
    rate: 4.7,
    totalrating: 765,
    price: 1099.00,
    discout: 8,
    size: "12.9 inches",
    variant: ["Space Gray", "Silver"],
    weight: "682g",
    brand: "Apple",
    delivery: "1-2 business days",
    description: "iPad Pro with M2 chip and Liquid Retina XDR display for stunning visuals.",
  },
  {
    id: 7,
    imges: Productimg,
    pCategory: "Audio & Headphones",
    pName: "Sony WH-1000XM5",
    rate: 4.8,
    totalrating: 2345,
    price: 399.99,
    discout: 25,
    size: "Adjustable headband",
    variant: ["Black", "Silver"],
    weight: "250g",
    brand: "Sony",
    delivery: "2-3 business days",
    description: "Industry-leading noise cancellation with 30-hour battery life and crystal clear hands-free calling.",
  },
  {
    id: 8,
    imges: Productimg,
    pCategory: "Audio & Headphones",
    pName: "Bose QuietComfort Ultra",
    rate: 4.6,
    totalrating: 987,
    price: 429.00,
    discout: 15,
    size: "Adjustable headband",
    variant: ["Black", "White"],
    weight: "253g",
    brand: "Bose",
    delivery: "3-5 business days",
    description: "Premium noise cancelling headphones with immersive audio and comfortable fit.",
  },
  {
    id: 9,
    imges: Productimg,
    pCategory: "Audio & Headphones",
    pName: "Apple AirPods Pro (2nd Gen)",
    rate: 4.5,
    totalrating: 3456,
    price: 249.00,
    discout: 10,
    size: "One size fits all",
    variant: ["White"],
    weight: "5.3g per earbud",
    brand: "Apple",
    delivery: "1-2 business days",
    description: "Active Noise Cancellation, Adaptive Audio, and up to 6 hours of battery life.",
  },
  {
    id: 10,
    imges: Productimg,
    pCategory: "Smart Watches",
    pName: "Apple Watch Ultra 2",
    rate: 4.7,
    totalrating: 1234,
    price: 799.00,
    discout: 5,
    size: "49mm",
    variant: ["Titanium"],
    weight: "61.3g",
    brand: "Apple",
    delivery: "1-2 business days",
    description: "The most rugged and capable Apple Watch with advanced fitness features and brightest display.",
  },
  {
    id: 11,
    imges: Productimg,
    pCategory: "Smart Watches",
    pName: "Samsung Galaxy Watch6 Classic",
    rate: 4.5,
    totalrating: 876,
    price: 429.99,
    discout: 20,
    size: "47mm",
    variant: ["Black", "Silver"],
    weight: "59g",
    brand: "Samsung",
    delivery: "2-3 business days",
    description: "Premium smartwatch with rotating bezel, advanced health monitoring, and long battery life.",
  },
  {
    id: 12,
    imges: Productimg,
    pCategory: "Smart Watches",
    pName: "Garmin Fenix 7",
    rate: 4.8,
    totalrating: 654,
    price: 699.99,
    discout: 15,
    size: "47mm",
    variant: ["Black", "Silver", "Gold"],
    weight: "79g",
    brand: "Garmin",
    delivery: "3-5 business days",
    description: "Multisport GPS watch with solar charging and advanced training metrics.",
  },
  {
    id: 13,
    imges: Productimg,
    pCategory: "Gaming",
    pName: "PlayStation 5",
    rate: 4.9,
    totalrating: 4567,
    price: 499.99,
    discout: 15,
    size: "15.4 x 10.2 x 4.1 inches",
    variant: ["Standard", "Digital Edition"],
    weight: "4.5kg",
    brand: "Sony",
    delivery: "1-3 business days",
    description: "Lightning speed, breathtaking immersion, and stunning games with the PS5 console.",
  },
  {
    id: 14,
    imges: Productimg,
    pCategory: "Gaming",
    pName: "Xbox Series X",
    rate: 4.8,
    totalrating: 3456,
    price: 499.99,
  discout: 15,
    size: "15.1 x 15.1 x 30.1 cm",
    variant: ["Standard"],
    weight: "4.45kg",
    brand: "Microsoft",
    delivery: "2-4 business days",
    description: "The fastest, most powerful Xbox ever with 12 teraflops of processing power.",
  },
  {
    id: 15,
    imges: Productimg,
    pCategory: "Gaming",
    pName: "Nintendo Switch OLED",
    rate: 4.7,
    totalrating: 2345,
    price: 349.99,
    discout: 10,
    size: "9.5 x 4 x 0.55 inches",
    variant: ["White", "Neon"],
    weight: "420g",
    brand: "Nintendo",
    delivery: "3-5 business days",
    description: "7-inch OLED screen, wide adjustable stand, and 64GB internal storage.",
  },

  {
    id: 16,
    imges: Productimg,
    pCategory: "Cameras",
    pName: "Sony A7 IV",
    rate: 4.9,
    totalrating: 876,
    price: 2499.00,
    discout: 8,
    size: "5.2 x 3.8 x 3.1 inches",
    variant: ["Body Only", "With Lens"],
    weight: "658g",
    brand: "Sony",
    delivery: "2-3 business days",
    description: "33MP full-frame mirrorless camera with 4K 60p video and advanced autofocus.",
  },
  {
    id: 17,
    imges: Productimg,
    pCategory: "Cameras",
    pName: "Canon EOS R5",
    rate: 4.8,
    totalrating: 765,
    price: 3899.00,
    discout: 5,
    size: "5.4 x 3.9 x 3.5 inches",
    variant: ["Body Only", "With Lens"],
    weight: "738g",
    brand: "Canon",
    delivery: "1-3 business days",
    description: "45MP full-frame mirrorless camera with 8K video and in-body stabilization.",
  },
  {
    id: 18,
    imges: Productimg,
    pCategory: "Cameras",
    pName: "Fujifilm X-T5",
    rate: 4.7,
    totalrating: 543,
    price: 1699.00,
    discout: 15,
    size: "5.1 x 3.6 x 2.5 inches",
    variant: ["Black", "Silver"],
    weight: "557g",
    brand: "Fujifilm",
    delivery: "3-5 business days",
    description: "40MP APS-C mirrorless camera with 6.2K video and classic Fujifilm controls.",
  },
  {
    id: 19,
    imges: Productimg,
    pCategory: "Phone",
    pName: "iPhone 15 Pro Max",
    rate: 4.7, 
    totalrating: 1248,
    price: 1199.99,
    discout: 10,
    size: "6.7 inches",
    variant: ["Space Black", "Titanium", "Silver"],
    weight: "221g",
    brand: "Apple",
    delivery: "1-2 business days",
    description: "The iPhone 15 Pro Max features a titanium design, A17 Pro chip, and the most advanced camera system ever on iPhone with a 5x Telephoto camera.",
  },{
    id: 20,
    imges: Productimg,
    pCategory: "Phone",
    pName: "iPhone 15 Pro Max",
    rate: 4.7, 
    totalrating: 1248,
    price: 1199.99,
    discout: 10,
    size: "6.7 inches",
    variant: ["Space Black", "Titanium", "Silver"],
    weight: "221g",
    brand: "Apple",
    delivery: "1-2 business days",
    description: "The iPhone 15 Pro Max features a titanium design, A17 Pro chip, and the most advanced camera system ever on iPhone with a 5x Telephoto camera.",
  }
];