import Productimg from "../../../../assets/Productimg/Productimg.webp"
export const Featureddata =[
   {
     id: 1,
     imges: Productimg,
     pCategory: "Phone",
     pName: "iPhone 14 Pro Max - 1",
     rate: 0.7, 
     totalrating: 48,
     price: 1121.53,
     discout: 51,
     size: "13.8 inches",
     variant: ["black", "green", "silver"],
     weight: "1.10kg",
     brand: "Samsung",
     delivery: "2-3 business days",
    description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
  },
  {
    id: 2,
    imges: Productimg,
    pCategory: "Computers & Tablets",
    pName: "iPhone 14 Pro Max - 2",
    rate: 3.0,
    totalrating: 375,
    price: 643.73,
    discout: 24,
    size: "13.8 inches",
    variant: ["black", "green", "silver"],
    weight: "1.10kg",
    brand: "Samsung",
    delivery: "2-3 business days",
    description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
  },
  {
    id: 3,
    imges: Productimg,
    pCategory: "Computers & Tablets",
    pName: "iPhone 14 Pro Max - 3",
    rate: 4.6,
    totalrating: 476,
    price: 379.96,
    discout: 36,
     size: "13.8 inches",
     variant: ["black", "green", "silver"],
     weight: "1.10kg",
     brand: "Samsung",
     delivery: "2-3 business days",
    description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
  },
  {
    id: 4,
    imges: Productimg,
    pCategory: "Audio & Headphones",
    pName: "iPhone 14 Pro Max - 4",
    rate: 2.3,
    totalrating: 260,
    price: 822.44,
    discout: 10,
     size: "13.8 inches",
     variant: ["black", "green", "silver"],
     weight: "1.10kg",
     brand: "Samsung",
     delivery: "2-3 business days",
    description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
  },
  {
    id: 5,
    imges: Productimg,
    pCategory: "Computers & Tablets",
    pName: "iPhone 14 Pro Max - 5",
    rate: 2.4,
    totalrating: 266,
    price: 61.26,
    discout: 42,
     size: "13.8 inches",
     variant: ["black", "green", "silver"],
     weight: "1.10kg",
     brand: "Samsung",
     delivery: "2-3 business days",
    description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
  },
  {
    id: 6,
    imges: Productimg,
    pCategory: "Audio & Headphones",
    pName: "iPhone 14 Pro Max - 6",
    rate: 4.0,
    totalrating: 101,
    price: 1370.06,
    discout: 15,
     size: "13.8 inches",
     variant: ["black", "green", "silver"],
     weight: "1.10kg",
     brand: "Samsung",
     delivery: "2-3 business days",
    description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
  },
  {
    id: 7,
    imges: Productimg,
    pCategory: "Computers & Tablets",
    pName: "iPhone 14 Pro Max - 7",
    rate: 3.2,
    totalrating: 417,
    price: 766.37,
    discout: 5,
     size: "13.8 inches",
     variant: ["black", "green", "silver"],
     weight: "1.10kg",
     brand: "Samsung",
     delivery: "2-3 business days",
    description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
  },
  {
    id: 8,
    imges: Productimg,
    pCategory: "Audio & Headphones",
    pName: "iPhone 14 Pro Max - 8",
    rate: 0.6,
    totalrating: 10,
    price: 1193.2,
    discout: 41,
     size: "13.8 inches",
     variant: ["black", "green", "silver"],
     weight: "1.10kg",
     brand: "Samsung",
     delivery: "2-3 business days",
    description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
  },
  {
    id: 9,
    imges: Productimg,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 9",
    rate: 3.9,
    totalrating: 213,
    price: 1342.52,
    discout: 29,
     size: "13.8 inches",
     variant: ["black", "green", "silver"],
     weight: "1.10kg",
     brand: "Samsung",
     delivery: "2-3 business days",
    description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
  },
  {
    id: 10,
    imges: Productimg,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 9",
    rate: 3.9,
    totalrating: 213,
    price: 1342.52,
    discout: 29,
     size: "13.8 inches",
     variant: ["black", "green", "silver"],
     weight: "1.10kg",
     brand: "Samsung",
     delivery: "2-3 business days",
    description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
  },
  {
    id: 11,
    imges: Productimg,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 9",
    rate: 3.9,
    totalrating: 213,
    price: 1342.52,
    discout: 29,
     size: "13.8 inches",
     variant: ["black", "green", "silver"],
     weight: "1.10kg",
     brand: "Samsung",
     delivery: "2-3 business days",
    description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
  },
  {
    id: 12,
    imges: Productimg,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 9",
    rate: 3.9,
    totalrating: 213,
    price: 1342.52,
    discout: 29,
     size: "13.8 inches",
     variant: ["black", "green", "silver"],
     weight: "1.10kg",
     brand: "Samsung",
     delivery: "2-3 business days",
    description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
  },
  {
    id: 13,
    imges: Productimg,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 9",
    rate: 3.9,
    totalrating: 213,
    price: 1342.52,
    discout: 29,
     size: "13.8 inches",
     variant: ["black", "green", "silver"],
     weight: "1.10kg",
     brand: "Samsung",
     delivery: "2-3 business days",
    description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
  },
  {
    id: 14,
    imges: Productimg,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 9",
    rate: 3.9,
    totalrating: 213,
    price: 1342.52,
    discout: 29,
     size: "13.8 inches",
     variant: ["black", "green", "silver"],
     weight: "1.10kg",
     brand: "Samsung",
     delivery: "2-3 business days",
    description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
  },
  {
    id: 15,
    imges: Productimg,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 9",
    rate: 3.9,
    totalrating: 213,
    price: 1342.52,
    discout: 29,
     size: "13.8 inches",
     variant: ["black", "green", "silver"],
     weight: "1.10kg",
     brand: "Samsung",
     delivery: "2-3 business days",
    description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
  },
  {
    id: 16,
    imges: Productimg,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 9",
    rate: 3.9,
    totalrating: 213,
    price: 1342.52,
    discout: 29,
     size: "13.8 inches",
     variant: ["black", "green", "silver"],
     weight: "1.10kg",
     brand: "Samsung",
     delivery: "2-3 business days",
    description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
  },
  {
    id: 17,
    imges: Productimg,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 9",
    rate: 3.9,
    totalrating: 213,
    price: 1342.52,
    discout: 29,
     size: "13.8 inches",
     variant: ["black", "green", "silver"],
     weight: "1.10kg",
     brand: "Samsung",
     delivery: "2-3 business days",
    description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
  },
  {
    id: 18,
    imges: Productimg,
    pCategory: "Phone",
    pName: "iPhone 14 Pro Max - 9",
    rate: 3.9,
    totalrating: 213,
    price: 1342.52,
    discout: 29,
     size: "13.8 inches",
     variant: ["black", "green", "silver"],
     weight: "1.10kg",
     brand: "Samsung",
     delivery: "2-3 business days",
    description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
  },
]