import Productimg from "../../../../assets/Productimg/Productimg.webp";

export const newproductdata = [
    {
        id: 1,
        imges: Productimg,
        pCatagori: "P H O N E",
        pName: "JPhone 13 High Quality..",
        rate: 1.5,
        totalrating: 120,
        price: 999.00,
        discount: 10,
    },
    {
        id: 2,
        imges: Productimg,
        pCatagori: "P H O N E",
        pName: "JPhone 13 Pro",
        rate: 1,
        totalrating: 120,
        price: 999.00,
        discount: null,
    },
    {
        id: 3,
        imges: Productimg,
        pCatagori: "P H O N E",
        pName: "JPhone 13 Max",
        rate: 3.8,
        totalrating: 120,
        price: 999.00,
        discount: 10,
    },
    {
        id: 4,
        imges: Productimg,
        pCatagori: "P H O N E",
        pName: "JPhone 13 Mini",
        rate: 5,
        totalrating: 120,
        price: 999.00,
        discount: 10,
    },
    {
        id: 5,
        imges: Productimg,
        pCatagori: "P H O N E",
        pName: "JPhone SE 2023",
        rate: 5,
        totalrating: 120,
        price: 999.00,
        discount: null,
    },
    {
        id: 6,
        imges: Productimg,
        pCatagori: "P H O N E",
        pName: "JPhone XR",
        rate: 4.5,
        totalrating: 98,
        price: 899.00,
        discount: 5,
    },
    {
        id: 7,
        imges: Productimg,
        pCatagori: "P H O N E",
        pName: "JPhone X",
        rate: 4.8,
        totalrating: 140,
        price: 1099.00,
        discount: 15,
    },
    {
        id: 8,
        imges: Productimg,
        pCatagori: "P H O N E",
        pName: "JPhone 11",
        rate: 4.2,
        totalrating: 102,
        price: 950.00,
        discount: 8,
    },
    {
        id: 9,
        imges: Productimg,
        pCatagori: "P H O N E",
        pName: "JPhone 12",
        rate: 4.6,
        totalrating: 132,
        price: 990.00,
        discount: null,
    },
    {
        id: 10,
        imges: Productimg,
        pCatagori: "P H O N E",
        pName: "JPhone Ultra",
        rate: 5,
        totalrating: 160,
        price: 1299.00,
        discount: 20,
    },
    {
        id: 11,
        imges: Productimg,
        pCatagori: "P H O N E",
        pName: "JPhone Max Pro",
        rate: 5,
        totalrating: 150,
        price: 1399.00,
        discount: 25,
    },
];
